version: '3'
services:
  blue:
    container_name: blue
    image: eojin0814/hicardi
#    expose:
#      - 8080
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
  green:
    container_name: green
    image: eojin0814/hicardi
#    expose:
#      - 8080
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
