spring:
  datasource:
    url: jdbc:mariadb://kusitms-cp-database.cn2nwe5snma7.ap-northeast-2.rds.amazonaws.com/hiCardiDb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 200MB
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE